### ISSUE TITLE
add "About the project" details on README

### ISSUE THREAD

**Issue by MarchandMD** [board-together/BE-Board-Together#14]
currently it's just some "lorem ipsum" text

It's possible to edit and create a pull request directly from Github (GH)

**Comment by the-amazing-atharva** [comment]
Hi!
I am a beginner here and would like to contribute

Could you just give one or two lines about the project so I can expand?

**Comment by MarchandMD** [comment]
@the-amazing-atharva Thanks for the interest!

We're working on an active group project that we're being critiqued for, so we'd like to honor our academic integrity policy until the project is due. 

Once we've submitted our project and received a response from our PM, we'll be opening the Repo to external contributions. 

Until then, please star the repo and keep an eye open for future issues!

**Comment by the-amazing-atharva** [comment]
Sure!
Thanks for the reply
