### ISSUE TITLE
BE—SETUP/DESIGN: Create DB Schema

### ISSUE THREAD

**Issue by ajpulzone** [board-together/BE-Board-Together#7]
Tentative Schema:

- Friends Table is tentative, may end up being an extension

[X] Users table to repo
[X] UsersGames table to repo
[X] Games table to repo
[  ] Add to README

![Image](https://user-images.githubusercontent.com/102780642/216471439-8e55dacf-807e-423c-b72e-8d98d5110b0d.png)

**Comment by MarchandMD** [comment]
Can this be added to the readme too?
